version: "3"
services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    networks:
      - private
      - public
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/log/traefik/traefik.log:/var/log/traefik/traefik.log
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    networks:
      - private
      - public
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    labels:
      - traefik.enabe=true
      - traefik.http.routers.plex.rule=Host(`plex.nzti.net`)
      - traefik.http.routers.plex.tls=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.tls.certresolver=le
    volumes:
      - /media/config:/config
      - /media/tv:/tv
      - /media/movies:/movies
      - /media/anime:/anime
    restart: unless-stopped

networks:
  public:
    driver: bridge
  private:
    driver: bridge
