version: "3"
services:
  traefik:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    networks:
      - private
      - public
    ports:
      - 880:80
      - 8443:443
      - 8080:8080
    volumes:
      - ./traefik.toml:/etc/traefik.toml
      - /etc/ssl/plex_key.pem:/etc/ssl/plex_key.pem
      - /etc/ssl/plex_cert.pem:/etc/ssl/plex_cert.pem
      - /var/run/docker.sock:/var/run/docker.sock
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    networks:
      - private
      - public
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    labels:
      - traefik.http.routers.plex.rule=Host(`nzti.plex.lab`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
    volumes:
      - /data/config:/config
      - /data/tv:/tv
      - /data/movies:/movies
    restart: unless-stopped

networks:
  public:
    driver: bridge
  private:
    driver: bridge
