# traefik.toml
[providers.docker]
[api]
  insecure = true

[retry]
  attempts = 3

defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http]
      [entryPoints.http.http.redirections]
        [entryPoints.http.http.redirections.entryPoint]
          to = "https"
          scheme = "https"
  [entryPoints.https]
    address = ":443"

[certificatesResolvers.le.acme]
  email = ""
  storage = "/letsencrypt/acme.json"
    [certificatesResolvers.le.acme.httpChallenge]
      entryPoint = "http"

[log]
  level = "DEBUG"
  filePath = "/var/log/traefik/traefik.log"
  format = "json"
