# traefik.toml
logLevel = "INFO"
traefikLogsFile = "log/traefik.log"
accessLogsFile = "log/access.log"

[retry]
	attempts = 3

defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/plex_key.pem"
      KeyFile = "/etc/ssl/plex_cert/pem"
